import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Menu from './Menu';

const Layout = ({ pages, children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.menu}>
          <Menu items={pages} />
        </div>
        <div className={styles.body}>
          <div>{children}</div>
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};
export default Layout;
